file_format: "1"
id: 6799FF
name: TO
type: shield
url: https://github.com/6799FF/amk-enki42-dongle
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - to_left
  - to_right
  - to_dongle
